version: '3'
services:
  mysql:
    container_name: prod-mysql
    image: mysql:5.7
    environment:
      TZ: Asia/Shanghai
      MYSQL_DATABASE: spring-boot
      MYSQL_ROOT_PASSWORD: A&*ODy9b&Pw10cDP
      MYSQL_ROOT_HOST: '%'
    ports:
      - "2345:3306"
    volumes:
      - /data/mysql-data:/var/lib/mysql
    restart: always

  test-example:
    container_name: prod-test-example
    build: ./
    ports:
      - "80:8443"
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis
    command: --spring.profiles.active=peer
    restart: always

  redis:
    container_name: prod-redis
    image: redis:4.0.8
    ports:
      - 5678:6379
    restart: always
    volumes:
      - /data/redis-data:/data
    command: redis-server --appendonly yes --requirepass "233"